/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a menuimporteradaptor -c MenuImporterAdaptor -i menuimporter.h com.canonical.AppMenu.Registrar.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */


#include "menuimporter.h"
#include "menuimporteradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MenuImporterAdaptor
 */

MenuImporterAdaptor::MenuImporterAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MenuImporterAdaptor::~MenuImporterAdaptor()
{
    // destructor
}

QString MenuImporterAdaptor::GetMenuForWindow(uint windowId, QDBusObjectPath &objectPath)
{

    // handle method call com.canonical.AppMenu.Registrar.GetMenuForWindow
    return static_cast<MenuImporter*>(parent())->GetMenuForWindow(windowId, objectPath);
}

void MenuImporterAdaptor::RegisterWindow(uint windowId, const QDBusObjectPath &menuObjectPath)
{
    qDebug() << __func__<<parent();
    // handle method call com.canonical.AppMenu.Registrar.RegisterWindow
    QMetaObject::invokeMethod(parent(), "RegisterWindow", Q_ARG(uint, windowId), Q_ARG(QDBusObjectPath, menuObjectPath));
}

void MenuImporterAdaptor::UnregisterWindow(uint windowId)
{
    qDebug()<<__func__;
    // handle method call com.canonical.AppMenu.Registrar.UnregisterWindow
    QMetaObject::invokeMethod(parent(), "UnregisterWindow", Q_ARG(uint, windowId));
}

